### ISSUE TITLE
not radar voice

### ISSUE THREAD

**Issue by cantera123** [TanguyOrtegat/esx_jb_radars#4]
does not skip the warning by radar voice and I have everything properly installed

**Comment by TanguyOrtegat** [comment]
i did not really inderstand, what is not happening ?

**Comment by cantera123** [comment]
when passing by a fixed radar, you can not hear the voice alert

**Comment by TanguyOrtegat** [comment]
what did you change ?

**Comment by cantera123** [comment]
I only change the sounds in French, for the ones in Spanish, all with the same name, for example Rf80.ogg ..

**Comment by TanguyOrtegat** [comment]
and does the script works well without any changes ?

**Comment by cantera123** [comment]
With the French voices, the script was not going either, which could be, if you want, I'll pass my script, if you have the problem

**Comment by TanguyOrtegat** [comment]
well, did you install dependency ? -_> ft_libs? 
This script does work so if you do not hear anything you did something wrong ...

**Comment by cantera123** [comment]
Yes, I have the dependency of ft_libs well installed, I do not understand why it could not be listened to, could you pass the code and made an eye?

**Comment by TanguyOrtegat** [comment]
install it like it is on github and test it out, are radars shown?

**Comment by cantera123** [comment]
I've tried it like it's on github and everything works, the radars look, and it sends fine fines, but no voice comes out when you go through one of them at the speed of alert

**Comment by TanguyOrtegat** [comment]
and what is the position you tried, did you try other positions ?

**Comment by cantera123** [comment]
I tried the radar from next to the police station

**Comment by TanguyOrtegat** [comment]
still not working?

**Comment by cantera123** [comment]
it still does not work

**Comment by TanguyOrtegat** [comment]
merged :)
