### ISSUE TITLE
J'arrive pas a faire marcher le script

### ISSUE THREAD

**Issue by Quegil72** [TanguyOrtegat/esx_jb_radars#5]
Bonjour, 
Le soucis que j'ai, est que j'ai un serveur five M et quand je met le script esx_js_radars et que je le start dans le serveur.cfg, c'est que quand je démarre le serveur et que je vais dessus et bah il n'y a aucun radars. est ce qu'il faut un  autre script avec ou pas comment bien le configure.
Moi je le place dans serveur-data, ressources, et dans [esx].
Svp besoin d'aide 
Merci

**Comment by Quegil72** [comment]
I can not make the script work

Hello,
The trouble I have, is that I have server five times that I met the script esx_js_radars and that I started in the server.cfg, it is when I wait for it and I go on it and well there is no radars. is needed another script with or comment well configure it.
I am in server-data, resources, and in [esx].
Please help
Thank you

**Comment by TanguyOrtegat** [comment]
ben t'as besoin une dependence a ft_libs...

**Comment by Quegil72** [comment]
donc il me faut le scipt ft libs ?


Le lun. 10 juin 2019 à 11:59, TanguyOrtegat <notifications@github.com> a
écrit :

**Comment by TanguyOrtegat** [comment]
si je parle pas chinois et que tu lis le readme oui...
