### ISSUE TITLE
Erreur MySQL

### ISSUE THREAD

**Issue by Venakiel** [TanguyOrtegat/esx_jb_radars#6]
Salut, voilà je rencontre un petit soucis, j'ai mis la ressource correctement mais j'ai une erreur MySQL dans la console serveur 
![esx_radar](https://user-images.githubusercontent.com/43210994/60680931-7e6a8c00-9e8d-11e9-97b1-f06aae0c77e3.PNG)

J'ai pourtant bien esx_billing, les radars sont bien en jeu mais j'ai l'impression qu'il ne peux pas insérer  la bdd

Merci pour ton aide

**Comment by TanguyOrtegat** [comment]
j'ai pas toute l'erreur donc je ne sais pas t'aider...

**Comment by Venakiel** [comment]
Salut, en faite c'est tout ce que j'ai dans la console serveur, et dans la console ingame j'ai rien.

**Comment by TanguyOrtegat** [comment]
ben va dans tes logs et copy colel tout ici

**Comment by TanguyOrtegat** [comment]
vu ne pas avoir de reaction, je supp le issue
