### ISSUE TITLE
Factures

### ISSUE THREAD

**Issue by MrGog0** [TanguyOrtegat/esx_jb_radars#9]
### Bonsoir, j'ai un problème avec les factures je ne les reçois pas voici l'erreur 

**[ERROR] [MySQL] An error happens on MySQL for query "INSERT INTO billing (identifier, sender, target_type, target, label, amount) VALUES (@identifier, @sender, @target_type, @target, @label, @amount) {@target_type=society;@amount=1500;@sender=Radar fixe;@target=society_police;@label=ðŸ“¸:plaque XKY 125 , 120 km/h a la place de 80.0;@identifier=steam:110000135c08c7e}": Incorrect string value: '\xF0\x9F\x93\xB8:p...' for column `zap423737-5`.`billing`.`label` at row 1**

Merci de vos réponse.

**Comment by TanguyOrtegat** [comment]
ceci est ton erreur : 
: Incorrect string value: '\xF0\x9F\x93\xB8:p

c'est ton emoji qui ne passe pas

**Comment by MrGog0** [comment]
Merci pour votre réponse comment est-ce que je pourrai l'enlever ?

**Comment by TanguyOrtegat** [comment]
Ben côté serveur
